export default [
  // 1
  {
    id: 1,
    position: 1,
    playlistId: 1,
    name: 'Come Over',
    price: 0.79,
    duration: 190,
  },
  {
    id: 2,
    position: 2,
    playlistId: 3,
    name: 'Begging',
    price: 0.79,
    duration: 231,
  },
  {
    id: 3,
    playlistId: 1,
    position: 3,
    name: 'Finders Keepers (feat. Kojo Funds)',
    price: 0.79,
    duration: 224,
  },
  {
    id: 4,
    playlistId: 1,
    position: 4,
    name: 'Ivy',
    price: 0.79,
    duration: 287,
  },
  {
    id: 5,
    position: 5,
    playlistId: 1,
    name: 'Low Key',
    price: 0.79,
    duration: 190,
  },
  {
    id: 6,
    position: 6,
    playlistId: 1,
    name: 'Roses',
    price: 0.79,
    duration: 231,
  },
  {
    id: 7,
    position: 7,
    playlistId: 1,
    name: 'Weapon',
    price: 0.79,
    duration: 224,
  },
  {
    id: 8,
    position: 8,
    playlistId: 1,
    name: 'Passionfruit',
    price: 0.79,
    duration: 287,
  },
  {
    id: 9,
    position: 9,
    playlistId: 1,
    name: 'Finders Keepers (feat. Kojo Funds, Burna Boy & Don-E)[Remix]',
    price: 0.79,
    duration: 190,
  },
];
