import { Playlist } from '../entity/Playlist';
import { Connection } from 'typeorm';

export default function playlistSeeds(seedersConneciton: Connection) {
  return seedersConneciton
    .createQueryBuilder()
    .insert()
    .into(Playlist)
    .values([
      {
        userId: 1,
        title: 'Ivy To Roses',
        price: 5.99,
        artwork:
          'https://i2.wp.com/s1.xclusivejams.com/2017/10/Mabel-Ivy-To-Roses-Mixtape-iTunes-Plus-M4A.jpg?w=640&ssl=1',
        permalink: 'ivy-to-roses',
        createdAt: new Date(),
        public: true,
        url: 'https://tunebay.com/username/permalink1',
      },
      {
        userId: 1,
        title: 'My Boy My Town',
        price: 0.99,
        artwork:
          'https://is2-ssl.mzstatic.com/image/thumb/Music122/v4/58/6e/51/586e51d3-6175-c286-a06b-7f2d007875f2/15UMGIM65453.jpg/1200x630bb.jpg',
        permalink: 'my-boy-my-town',
        createdAt: new Date(),
        public: true,
        url: 'https://tunebay.com/username/permalink2',
      },
      {
        userId: 1,
        title: 'Thinking Of You',
        price: 5.99,
        artwork:
          'https://images.genius.com/122c310b162d72c5d271d32753b5fa60.630x630x1.jpg',
        permalink: 'thinking-of-you',
        createdAt: new Date(),
        public: true,
        url: 'https://tunebay.com/username/permalink3',
      },
      {
        userId: 1,
        title: 'Finders Keepers',
        price: 5.99,
        artwork: 'https://pbs.twimg.com/profileImages/862396484658057223/0RDeiaKc.jpg',
        permalink: 'finders-keepers',
        createdAt: new Date(),
        public: true,
        url: 'https://tunebay.com/username/permalink4',
      },
      {
        userId: 2,
        title: 'Love + War',
        price: 5.99,
        artwork: 'https://i1.sndcdn.com/artworks-0hDPbHUtMjWO-0-t500x500.jpg',
        permalink: 'love-war',
        createdAt: new Date(),
        public: true,
        url: 'https://tunebay.com/username/permalink5',
      },
      {
        userId: 2,
        title: 'Cheating On Me',
        price: 5.99,
        artwork: 'https://i1.sndcdn.com/artworks-000138126630-gops5c-t500x500.jpg',
        permalink: 'cheating-on-me',
        createdAt: new Date(),
        public: true,
        url: 'https://tunebay.com/username/permalink6',
      },
      {
        userId: 2,
        title: 'Walk',
        price: 5.99,
        artwork: 'https://i1.sndcdn.com/artworks-wylrh6pNAk2b-0-t500x500.jpg',
        permalink: 'walk',
        createdAt: new Date(),
        public: true,
        url: 'https://tunebay.com/username/permalink7',
      },
      {
        userId: 3,
        title: 'When Ur Sober',
        price: 5.99,
        artwork: 'https://i1.sndcdn.com/artworks-7xbVEf5nJf1s-0-t500x500.jpg',
        permalink: 'when-ur-sober',
        createdAt: new Date(),
        public: true,
        url: 'https://tunebay.com/username/permalink8',
      },
      {
        userId: 3,
        title: 'Redlight',
        price: 5.99,
        artwork:
          'https://i1.sndcdn.com/artworks-b2350727-2418-480b-87c0-47178c030ea2-0-t500x500.jpg',
        permalink: 'redlight',
        createdAt: new Date(),
        public: true,
        url: 'https://tunebay.com/username/permalink9',
      },
      {
        userId: 3,
        title: 'Deeper',
        price: 5.99,
        artwork: 'https://i1.sndcdn.com/artworks-S5enoBO1t7ca-0-t500x500.jpg',
        permalink: 'deeper',
        createdAt: new Date(),
        public: true,
        url: 'https://tunebay.com/username/permalink10',
      },
      {
        userId: 4,
        title: 'Something For Your M.I.N.D',
        price: 5.99,
        artwork: 'https://i1.sndcdn.com/artworks-NeORKaFfnXy0-0-t500x500.png',
        permalink: 'something-for-your-mind',
        createdAt: new Date(),
        public: true,
        url: 'https://tunebay.com/username/permalink11',
      },
      {
        userId: 4,
        title: 'Nobody Cares',
        price: 5.99,
        artwork: 'https://i1.sndcdn.com/artworks-w1rexXd0Krku-0-t500x500.png',
        permalink: 'nobody-cares',
        createdAt: new Date(),
        public: true,
        url: 'https://tunebay.com/username/permalink12',
      },
      {
        userId: 5,
        title: "Shake's On A Plane ",
        price: 5.99,
        artwork: 'https://i1.sndcdn.com/artworks-000246329913-s5iwvy-t500x500.jpg',
        permalink: 'shakes-on-a-plane',
        createdAt: new Date(),
        public: true,
        url: 'https://tunebay.com/username/permalink13',
      },
      {
        userId: 5,
        title: 'Northern Merry',
        price: 5.99,
        artwork: 'https://i1.sndcdn.com/artworks-000142313354-20yxz2-t500x500.jpg',
        permalink: 'nothern-merry',
        createdAt: new Date(),
        public: true,
        url: 'https://tunebay.com/username/permalink14',
      },
    ]);
}
