module.exports = {
  up: (queryInterface, Sequelize) =>
    queryInterface.bulkInsert(
      'users',
      [
        {
          name: 'Mabel',
          username: 'mabel',
          bio: '🚀 Just out here writing fake bios that are at least 2 lines long',
          cover_photo: 'https://i1.sndcdn.com/visuals-000161652148-8uID1y-t2480x520.jpg',
          profile_picture: 'https://hamadamania.files.wordpress.com/2017/03/mabel08.jpg',
          provider: 'email',
          email: 'mabel@mabel.com',
          password: 'Sup3rS3cr3t',
          created_at: new Date(),
        },
        {
          name: 'Kwabs',
          username: 'kwabs',
          bio: '🚀 Just out here writing fake bios that are at least 2 lines long',
          cover_photo: 'https://i1.sndcdn.com/visuals-000002842378-gQ9HT3-t2480x520.jpg',
          profile_picture: 'https://i1.sndcdn.com/avatars-000129316563-iqfoha-t500x500.jpg',
          provider: 'email',
          email: 'kwabs@kwabs.com',
          password: 'Sup3rS3cr3t',
          created_at: new Date(),
        },
        {
          name: 'Taya',
          username: 'taya',
          bio: '🚀 Just out here writing fake bios that are at least 2 lines long',
          cover_photo: 'https://i1.sndcdn.com/visuals-000024328107-Rz0BGo-t2480x520.jpg',
          profile_picture: 'https://i1.sndcdn.com/avatars-000332530388-c4w465-t500x500.jpg',
          provider: 'google',
          email: 'taya@gmail.com',
          password: 'Sup3rS3cr3t',
          created_at: new Date(),
        },
        {
          name: 'Super-organism',
          username: 'superorganism',
          bio: '🚀 Just out here writing fake bios that are at least 2 lines long',
          cover_photo: 'https://i1.sndcdn.com/visuals-000280613089-o3KIxO-t2480x520.jpg',
          profile_picture: 'https://i1.sndcdn.com/avatars-000291846497-whxcmc-t500x500.jpg',
          provider: 'facebook',
          email: 'superorganism@facebook.com',
          password: 'Sup3rS3cr3t',
          created_at: new Date(),
        },
        {
          name: 'Dan Shake',
          username: 'danshake',
          bio: '🚀 Just out here writing fake bios that are at least 2 lines long',
          cover_photo: 'https://i1.sndcdn.com/visuals-000017457541-BH5eIh-t2480x520.jpg',
          profile_picture: 'https://i1.sndcdn.com/avatars-000115448975-e9t5cp-t500x500.jpg',
          provider: 'google',
          email: 'danshake@gmail.com',
          password: 'Sup3rS3cr3t',
          created_at: new Date(),
        },
      ],
      {},
    ),

  down: (queryInterface, Sequelize) => queryInterface.bulkDelete('users', null, {}),
};
