module.exports = {
  up: (queryInterface, Sequelize) =>
    queryInterface.bulkInsert(
      'tracks',
      [
        {
          playlist_position: 1,
          playlist_id: 1,
          title: 'Come Over',
          price: 0.79,
          duration: 190,
          created_at: new Date(),
        },
        {
          playlist_id: 1,
          playlist_position: 2,
          title: 'Begging',
          price: 0.79,
          duration: 231,
          created_at: new Date(),
        },
        {
          playlist_id: 1,
          playlist_position: 3,
          title: 'Finders Keepers (feat. Kojo Funds)',
          price: 0.79,
          duration: 224,
          created_at: new Date(),
        },
        {
          playlist_id: 1,
          playlist_position: 4,
          title: 'Ivy',
          price: 0.79,
          duration: 287,
          created_at: new Date(),
        },
        {
          playlist_position: 5,
          playlist_id: 1,
          title: 'Low Key',
          price: 0.79,
          duration: 190,
          created_at: new Date(),
        },
        {
          playlist_position: 6,
          playlist_id: 1,
          title: 'Roses',
          price: 0.79,
          duration: 231,
          created_at: new Date(),
        },
        {
          playlist_position: 7,
          playlist_id: 1,
          title: 'Weapon',
          price: 0.79,
          duration: 224,
          created_at: new Date(),
        },
        {
          playlist_position: 8,
          playlist_id: 1,
          title: 'Passionfruit',
          price: 0.79,
          duration: 287,
          created_at: new Date(),
        },
        {
          playlist_position: 9,
          playlist_id: 1,
          title: 'Finders Keepers (feat. Kojo Funds, Burna Boy & Don-E)[Remix]',
          price: 0.79,
          duration: 190,
          created_at: new Date(),
        },
        {
          playlist_position: 1,
          playlist_id: 2,
          title: 'Come Over',
          price: 0.79,
          duration: 190,
          created_at: new Date(),
        },
        {
          playlist_id: 2,
          playlist_position: 2,
          title: 'Begging',
          price: 0.79,
          duration: 231,
          created_at: new Date(),
        },
        {
          playlist_id: 2,
          playlist_position: 3,
          title: 'Finders Keepers (feat. Kojo Funds)',
          price: 0.79,
          duration: 224,
          created_at: new Date(),
        },
        {
          playlist_id: 3,
          playlist_position: 1,
          title: 'Ivy',
          price: 0.79,
          duration: 287,
          created_at: new Date(),
        },
        {
          playlist_id: 4,
          playlist_position: 1,
          title: 'Low Key',
          price: 0.79,
          duration: 190,
          created_at: new Date(),
        },
        {
          playlist_id: 4,
          playlist_position: 2,
          title: 'Roses',
          price: 0.79,
          duration: 231,
          created_at: new Date(),
        },
        {
          playlist_id: 4,
          playlist_position: 3,
          title: 'Weapon',
          price: 0.79,
          duration: 224,
          created_at: new Date(),
        },
        {
          playlist_id: 5,
          playlist_position: 1,
          title: 'Passionfruit',
          price: 0.79,
          duration: 287,
          created_at: new Date(),
        },
        {
          playlist_id: 5,
          playlist_position: 2,
          title: 'Finders Keepers (feat. Kojo Funds, Burna Boy & Don-E)[Remix]',
          price: 0.79,
          duration: 190,
          created_at: new Date(),
        },
        {
          playlist_position: 3,
          playlist_id: 5,
          title: 'Finders Keepers (feat. Kojo Funds, Burna Boy & Don-E)[Remix]',
          price: 0.79,
          duration: 190,
          created_at: new Date(),
        },
        {
          playlist_position: 1,
          playlist_id: 6,
          title: 'New Name',
          price: 0.79,
          duration: 190,
          created_at: new Date(),
        },
        {
          playlist_position: 1,
          playlist_id: 7,
          title: 'New Name',
          price: 0.79,
          duration: 190,
          created_at: new Date(),
        },
        {
          playlist_position: 1,
          playlist_id: 8,
          title: 'New Name',
          price: 0.79,
          duration: 190,
          created_at: new Date(),
        },
        {
          playlist_position: 1,
          playlist_id: 9,
          title: 'New Name',
          price: 0.79,
          duration: 190,
          created_at: new Date(),
        },
        {
          playlist_position: 1,
          playlist_id: 10,
          title: 'New Name',
          price: 0.79,
          duration: 190,
          created_at: new Date(),
        },
        {
          playlist_position: 1,
          playlist_id: 11,
          title: 'New Name',
          price: 0.79,
          duration: 190,
          created_at: new Date(),
        },
        {
          playlist_position: 2,
          playlist_id: 11,
          title: 'New Name',
          price: 0.79,
          duration: 190,
          created_at: new Date(),
        },
        {
          playlist_position: 1,
          playlist_id: 12,
          title: 'New Name',
          price: 0.79,
          duration: 190,
          created_at: new Date(),
        },
      ],
      {},
    ),

  down: (queryInterface, Sequelize) => queryInterface.bulkDelete('tracks', null, {}),
};
